# thre weeks without any progress / comments mark issue as stale
daysUntilStale: 21
# one week after marked stale, close the issue
daysUntilClose: 14
staleLabel: no-recent-activity
# whitelist of lables to not mark stale
exemptLables:
  - feature
  - security
  - enhancement
# text of the comment when marking issue as stale
markComment: >
  This issue has been automatically labled because it has not had recent activity. If you have not received a response from anyone, please mention the repository maintainer (most likely @jbaxleyiii). It will be closed if no further activity occurs. Thank you for your contributions to React Apollo!
# text of the comment when closing an issue
closeComment: >
  This issue has been automatically closed because it has not had recent activity after being marked as no recent activyt. If you belive this issue is still a problem or should be reopened, please reopen it! Thank you for your contributions to React Apollo!
