// Generated by typings
// Source: https://raw.githubusercontent.com/louy/typed-object-assign/91dd2548172cee5dc0aa531d1b452a76044dbff2/index.d.ts
declare module '~object-assign/index' {
function assign<A extends Object>(a: A): A;
function assign<A extends Object, B>(a: A, b: B): A & B;
function assign<A extends Object, B, C>(a: A, b: B, c: C): A & B & C;
function assign<A extends Object, B, C, D>(a: A, b: B, c: C, d: D): A & B & C & D;
function assign<A extends Object, B, C, D, E>(a: A, b: B, c: C, d: D, e: E): A & B & C & D & E;
function assign<A extends Object>(...a: A[]): A;

export = assign;
}
declare module 'object-assign/index' {
import main = require('~object-assign/index');
export = main;
}
declare module 'object-assign' {
import main = require('~object-assign/index');
export = main;
}
