// flow-typed signature: 8321530d72e86ab95eec085a74170df8
// flow-typed version: <<STUB>>/@types/enzyme_v^2.4.32/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/enzyme' {
  declare module.exports: any;
}
