// flow-typed signature: f51eb9f045744ba65f8e8189bcea9d81
// flow-typed version: <<STUB>>/@types/graphql_v^0.9.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/graphql' {
  declare module.exports: any;
}
