// flow-typed signature: 1545e5173c92982b962e92de621f32f5
// flow-typed version: <<STUB>>/@types/invariant_v^2.2.27/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/invariant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/invariant' {
  declare module.exports: any;
}
