// flow-typed signature: 336228a4339a29f4e75391da25bc1552
// flow-typed version: <<STUB>>/@types/isomorphic-fetch_v0.0.34/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/isomorphic-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/isomorphic-fetch' {
  declare module.exports: any;
}
