// flow-typed signature: 522fe071fedf2fd8fea69ca6e0a75faa
// flow-typed version: <<STUB>>/@types/lodash_v^4.14.36/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/lodash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/lodash' {
  declare module.exports: any;
}
