// flow-typed signature: 8ebd8ef35cc6b290c4e9fc1402ac1fdd
// flow-typed version: <<STUB>>/@types/object-assign_v^4.0.28/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/object-assign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/object-assign' {
  declare module.exports: any;
}
