// flow-typed signature: 54b3bc0c54adca3dab343c2672af2a74
// flow-typed version: <<STUB>>/@types/react_v^15.0.12/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
