// flow-typed signature: 4a8ba350d9c41ba363f161c1a05583af
// flow-typed version: <<STUB>>/@types/react-addons-test-utils_v^0.14.14/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-addons-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-addons-test-utils' {
  declare module.exports: any;
}
