// flow-typed signature: f76bc420ffb3720cca5524247b1c41e5
// flow-typed version: <<STUB>>/@types/redux-form_v^6.3.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/redux-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/redux-form' {
  declare module.exports: any;
}
