// flow-typed signature: 3ea73e2b4f38602384c68df54cba6492
// flow-typed version: <<STUB>>/@types/redux-immutable_v^3.0.30/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/redux-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/redux-immutable' {
  declare module.exports: any;
}
