// flow-typed signature: 2bcf7f8ce8a77bdddfbbb76a0a448e62
// flow-typed version: <<STUB>>/@types/sinon_v^2.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/sinon' {
  declare module.exports: any;
}
