// flow-typed signature: b70d7e3ae32fdc39a6a64d4092b285ea
// flow-typed version: <<STUB>>/jest-react-native_v18.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-react-native/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-react-native/build/index.js' {
  declare module.exports: $Exports<'jest-react-native/build/index'>;
}
