// flow-typed signature: 402551f391466c35cc9090530656a0e7
// flow-typed version: <<STUB>>/lodash.pick_v^4.4.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.pick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.pick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.pick/index' {
  declare module.exports: $Exports<'lodash.pick'>;
}
declare module 'lodash.pick/index.js' {
  declare module.exports: $Exports<'lodash.pick'>;
}
