// flow-typed signature: ff752c1ed0e57d8de024bc7ae51e6c02
// flow-typed version: <<STUB>>/lodash.isobject_v^3.0.2/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.isobject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.isobject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.isobject/index' {
  declare module.exports: $Exports<'lodash.isobject'>;
}
declare module 'lodash.isobject/index.js' {
  declare module.exports: $Exports<'lodash.isobject'>;
}
