// flow-typed signature: 0ad4055bd60da286aea947ef1515023c
// flow-typed version: <<STUB>>/lodash.isequal_v^4.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.isequal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.isequal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.isequal/index' {
  declare module.exports: $Exports<'lodash.isequal'>;
}
declare module 'lodash.isequal/index.js' {
  declare module.exports: $Exports<'lodash.isequal'>;
}
