// flow-typed signature: a46744077bca0680f4334aeb5f4be40f
// flow-typed version: <<STUB>>/redux_v^2.0.0 || ^3.0.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux/dist/redux' {
  declare module.exports: any;
}

declare module 'redux/dist/redux.min' {
  declare module.exports: any;
}

declare module 'redux/es/applyMiddleware' {
  declare module.exports: any;
}

declare module 'redux/es/bindActionCreators' {
  declare module.exports: any;
}

declare module 'redux/es/combineReducers' {
  declare module.exports: any;
}

declare module 'redux/es/compose' {
  declare module.exports: any;
}

declare module 'redux/es/createStore' {
  declare module.exports: any;
}

declare module 'redux/es/index' {
  declare module.exports: any;
}

declare module 'redux/es/utils/warning' {
  declare module.exports: any;
}

declare module 'redux/lib/applyMiddleware' {
  declare module.exports: any;
}

declare module 'redux/lib/bindActionCreators' {
  declare module.exports: any;
}

declare module 'redux/lib/combineReducers' {
  declare module.exports: any;
}

declare module 'redux/lib/compose' {
  declare module.exports: any;
}

declare module 'redux/lib/createStore' {
  declare module.exports: any;
}

declare module 'redux/lib/index' {
  declare module.exports: any;
}

declare module 'redux/lib/utils/warning' {
  declare module.exports: any;
}

declare module 'redux/src/applyMiddleware' {
  declare module.exports: any;
}

declare module 'redux/src/bindActionCreators' {
  declare module.exports: any;
}

declare module 'redux/src/combineReducers' {
  declare module.exports: any;
}

declare module 'redux/src/compose' {
  declare module.exports: any;
}

declare module 'redux/src/createStore' {
  declare module.exports: any;
}

declare module 'redux/src/index' {
  declare module.exports: any;
}

declare module 'redux/src/utils/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux/dist/redux.js' {
  declare module.exports: $Exports<'redux/dist/redux'>;
}
declare module 'redux/dist/redux.min.js' {
  declare module.exports: $Exports<'redux/dist/redux.min'>;
}
declare module 'redux/es/applyMiddleware.js' {
  declare module.exports: $Exports<'redux/es/applyMiddleware'>;
}
declare module 'redux/es/bindActionCreators.js' {
  declare module.exports: $Exports<'redux/es/bindActionCreators'>;
}
declare module 'redux/es/combineReducers.js' {
  declare module.exports: $Exports<'redux/es/combineReducers'>;
}
declare module 'redux/es/compose.js' {
  declare module.exports: $Exports<'redux/es/compose'>;
}
declare module 'redux/es/createStore.js' {
  declare module.exports: $Exports<'redux/es/createStore'>;
}
declare module 'redux/es/index.js' {
  declare module.exports: $Exports<'redux/es/index'>;
}
declare module 'redux/es/utils/warning.js' {
  declare module.exports: $Exports<'redux/es/utils/warning'>;
}
declare module 'redux/lib/applyMiddleware.js' {
  declare module.exports: $Exports<'redux/lib/applyMiddleware'>;
}
declare module 'redux/lib/bindActionCreators.js' {
  declare module.exports: $Exports<'redux/lib/bindActionCreators'>;
}
declare module 'redux/lib/combineReducers.js' {
  declare module.exports: $Exports<'redux/lib/combineReducers'>;
}
declare module 'redux/lib/compose.js' {
  declare module.exports: $Exports<'redux/lib/compose'>;
}
declare module 'redux/lib/createStore.js' {
  declare module.exports: $Exports<'redux/lib/createStore'>;
}
declare module 'redux/lib/index.js' {
  declare module.exports: $Exports<'redux/lib/index'>;
}
declare module 'redux/lib/utils/warning.js' {
  declare module.exports: $Exports<'redux/lib/utils/warning'>;
}
declare module 'redux/src/applyMiddleware.js' {
  declare module.exports: $Exports<'redux/src/applyMiddleware'>;
}
declare module 'redux/src/bindActionCreators.js' {
  declare module.exports: $Exports<'redux/src/bindActionCreators'>;
}
declare module 'redux/src/combineReducers.js' {
  declare module.exports: $Exports<'redux/src/combineReducers'>;
}
declare module 'redux/src/compose.js' {
  declare module.exports: $Exports<'redux/src/compose'>;
}
declare module 'redux/src/createStore.js' {
  declare module.exports: $Exports<'redux/src/createStore'>;
}
declare module 'redux/src/index.js' {
  declare module.exports: $Exports<'redux/src/index'>;
}
declare module 'redux/src/utils/warning.js' {
  declare module.exports: $Exports<'redux/src/utils/warning'>;
}
