// flow-typed signature: 1005848f13bfd43a9ba7af84f3663c5c
// flow-typed version: <<STUB>>/swapi-graphql_v0.0.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swapi-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swapi-graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swapi-graphql/lib/api/cachedData/cache' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/api/cachedData/downloadCache' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/api/index' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/api/local' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/api/remote' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/index' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/apiHelper' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/commonFields' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/connections' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/index' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/relayNode' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/types/film' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/types/person' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/types/planet' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/types/species' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/types/starship' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/schema/types/vehicle' {
  declare module.exports: any;
}

declare module 'swapi-graphql/lib/server/main' {
  declare module.exports: any;
}

declare module 'swapi-graphql/scripts/mocha-bootload' {
  declare module.exports: any;
}

declare module 'swapi-graphql/scripts/print-schema' {
  declare module.exports: any;
}

declare module 'swapi-graphql/scripts/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swapi-graphql/lib/api/cachedData/cache.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/api/cachedData/cache'>;
}
declare module 'swapi-graphql/lib/api/cachedData/downloadCache.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/api/cachedData/downloadCache'>;
}
declare module 'swapi-graphql/lib/api/index.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/api/index'>;
}
declare module 'swapi-graphql/lib/api/local.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/api/local'>;
}
declare module 'swapi-graphql/lib/api/remote.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/api/remote'>;
}
declare module 'swapi-graphql/lib/index.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/index'>;
}
declare module 'swapi-graphql/lib/schema/apiHelper.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/apiHelper'>;
}
declare module 'swapi-graphql/lib/schema/commonFields.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/commonFields'>;
}
declare module 'swapi-graphql/lib/schema/connections.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/connections'>;
}
declare module 'swapi-graphql/lib/schema/index.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/index'>;
}
declare module 'swapi-graphql/lib/schema/relayNode.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/relayNode'>;
}
declare module 'swapi-graphql/lib/schema/types/film.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/types/film'>;
}
declare module 'swapi-graphql/lib/schema/types/person.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/types/person'>;
}
declare module 'swapi-graphql/lib/schema/types/planet.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/types/planet'>;
}
declare module 'swapi-graphql/lib/schema/types/species.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/types/species'>;
}
declare module 'swapi-graphql/lib/schema/types/starship.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/types/starship'>;
}
declare module 'swapi-graphql/lib/schema/types/vehicle.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/schema/types/vehicle'>;
}
declare module 'swapi-graphql/lib/server/main.js' {
  declare module.exports: $Exports<'swapi-graphql/lib/server/main'>;
}
declare module 'swapi-graphql/scripts/mocha-bootload.js' {
  declare module.exports: $Exports<'swapi-graphql/scripts/mocha-bootload'>;
}
declare module 'swapi-graphql/scripts/print-schema.js' {
  declare module.exports: $Exports<'swapi-graphql/scripts/print-schema'>;
}
declare module 'swapi-graphql/scripts/watch.js' {
  declare module.exports: $Exports<'swapi-graphql/scripts/watch'>;
}
