// flow-typed signature: 5624d1eb8f9c44fe1d8561b66f4a82d2
// flow-typed version: <<STUB>>/travis-weigh-in_v1.0.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'travis-weigh-in'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'travis-weigh-in' {
  declare module.exports: any;
}
