// flow-typed signature: 9007227365a898d964deeabfd9aa392d
// flow-typed version: <<STUB>>/travis-weigh-in_v^1.0.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'travis-weigh-in'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'travis-weigh-in' {
  declare module.exports: any;
}
