// flow-typed signature: 6f4bf46dada53ae37ed459739372417f
// flow-typed version: <<STUB>>/ts-jest_v20.0.14/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ts-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ts-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ts-jest/dist/default-retrieve-file-handler' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/index' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/jest-types' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/postprocess' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/preprocessor' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/transpile-if-ts' {
  declare module.exports: any;
}

declare module 'ts-jest/dist/utils' {
  declare module.exports: any;
}

declare module 'ts-jest/preprocessor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ts-jest/dist/default-retrieve-file-handler.js' {
  declare module.exports: $Exports<
    'ts-jest/dist/default-retrieve-file-handler',
  >;
}
declare module 'ts-jest/dist/index.js' {
  declare module.exports: $Exports<'ts-jest/dist/index'>;
}
declare module 'ts-jest/dist/jest-types.js' {
  declare module.exports: $Exports<'ts-jest/dist/jest-types'>;
}
declare module 'ts-jest/dist/postprocess.js' {
  declare module.exports: $Exports<'ts-jest/dist/postprocess'>;
}
declare module 'ts-jest/dist/preprocessor.js' {
  declare module.exports: $Exports<'ts-jest/dist/preprocessor'>;
}
declare module 'ts-jest/dist/transpile-if-ts.js' {
  declare module.exports: $Exports<'ts-jest/dist/transpile-if-ts'>;
}
declare module 'ts-jest/dist/utils.js' {
  declare module.exports: $Exports<'ts-jest/dist/utils'>;
}
declare module 'ts-jest/index' {
  declare module.exports: $Exports<'ts-jest'>;
}
declare module 'ts-jest/index.js' {
  declare module.exports: $Exports<'ts-jest'>;
}
declare module 'ts-jest/preprocessor.js' {
  declare module.exports: $Exports<'ts-jest/preprocessor'>;
}
