// flow-typed signature: c84d7924ba0ea2984ae14f075a2d2f20
// flow-typed version: <<STUB>>/typescript-require_v^0.2.9-1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescript-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescript-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typescript-require/test/require' {
  declare module.exports: any;
}

declare module 'typescript-require/tmp/tsreq/test/assets/ship' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typescript-require/index' {
  declare module.exports: $Exports<'typescript-require'>;
}
declare module 'typescript-require/index.js' {
  declare module.exports: $Exports<'typescript-require'>;
}
declare module 'typescript-require/test/require.js' {
  declare module.exports: $Exports<'typescript-require/test/require'>;
}
declare module 'typescript-require/tmp/tsreq/test/assets/ship.js' {
  declare module.exports: $Exports<'typescript-require/tmp/tsreq/test/assets/ship'>;
}
