// flow-typed signature: 301f4f0b7b2b8f992d07b6c005095806
// flow-typed version: <<STUB>>/typescript-require_v0.2.9/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescript-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescript-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typescript-require/test/require' {
  declare module.exports: any;
}

declare module 'typescript-require/tmp/tsreq/test/assets/ship' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typescript-require/index' {
  declare module.exports: $Exports<'typescript-require'>;
}
declare module 'typescript-require/index.js' {
  declare module.exports: $Exports<'typescript-require'>;
}
declare module 'typescript-require/test/require.js' {
  declare module.exports: $Exports<'typescript-require/test/require'>;
}
declare module 'typescript-require/tmp/tsreq/test/assets/ship.js' {
  declare module.exports: $Exports<
    'typescript-require/tmp/tsreq/test/assets/ship',
  >;
}
