// flow-typed signature: 7b3bd4bb585b73cf9d3db43a26bd76b9
// flow-typed version: <<STUB>>/typings_v^2.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typings/dist/aliases' {
  declare module.exports: any;
}

declare module 'typings/dist/bin-bundle' {
  declare module.exports: any;
}

declare module 'typings/dist/bin-init' {
  declare module.exports: any;
}

declare module 'typings/dist/bin-install' {
  declare module.exports: any;
}

declare module 'typings/dist/bin-list' {
  declare module.exports: any;
}

declare module 'typings/dist/bin-open' {
  declare module.exports: any;
}

declare module 'typings/dist/bin-prune' {
  declare module.exports: any;
}

declare module 'typings/dist/bin-search' {
  declare module.exports: any;
}

declare module 'typings/dist/bin-uninstall' {
  declare module.exports: any;
}

declare module 'typings/dist/bin-view' {
  declare module.exports: any;
}

declare module 'typings/dist/bin' {
  declare module.exports: any;
}

declare module 'typings/dist/support/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typings/dist/aliases.js' {
  declare module.exports: $Exports<'typings/dist/aliases'>;
}
declare module 'typings/dist/bin-bundle.js' {
  declare module.exports: $Exports<'typings/dist/bin-bundle'>;
}
declare module 'typings/dist/bin-init.js' {
  declare module.exports: $Exports<'typings/dist/bin-init'>;
}
declare module 'typings/dist/bin-install.js' {
  declare module.exports: $Exports<'typings/dist/bin-install'>;
}
declare module 'typings/dist/bin-list.js' {
  declare module.exports: $Exports<'typings/dist/bin-list'>;
}
declare module 'typings/dist/bin-open.js' {
  declare module.exports: $Exports<'typings/dist/bin-open'>;
}
declare module 'typings/dist/bin-prune.js' {
  declare module.exports: $Exports<'typings/dist/bin-prune'>;
}
declare module 'typings/dist/bin-search.js' {
  declare module.exports: $Exports<'typings/dist/bin-search'>;
}
declare module 'typings/dist/bin-uninstall.js' {
  declare module.exports: $Exports<'typings/dist/bin-uninstall'>;
}
declare module 'typings/dist/bin-view.js' {
  declare module.exports: $Exports<'typings/dist/bin-view'>;
}
declare module 'typings/dist/bin.js' {
  declare module.exports: $Exports<'typings/dist/bin'>;
}
declare module 'typings/dist/support/cli.js' {
  declare module.exports: $Exports<'typings/dist/support/cli'>;
}
