// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/npm-invariant/58403cee078ebef52112c4227c4d23a97821ef5c/invariant.d.ts
declare module '~invariant/invariant' {
function invariant (condition: boolean, message: string, ...args: string[]): void;

export = invariant;
}
declare module 'invariant/invariant' {
import main = require('~invariant/invariant');
export = main;
}
declare module 'invariant' {
import main = require('~invariant/invariant');
export = main;
}
