// Generated by typings
// Source: ambient.d.ts
declare module "lodash.isobject" {
  import main = require('~lodash/index');
  // export = main.isObject;
  public isObject = main.isObject;
}

declare module "lodash.isequal" {
  import main = require('~lodash/index');
  // export = main.isEqual;
  public isEqual = main.isEqual;
}